version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
      - "dkrutskikh"
    commit-message:
      prefix: "chore: "

  # Maintain Docker images used in GitHub Actions
  - package-ecosystem: "docker"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    assignees:
      - "dependabot"
      - "dkrutskikh"
    commit-message:
      prefix: "chore: "
