version = 1

# ğŸ” Common analyzer - for main source code
[[analyzers]]
name = "cxx-sources"
enabled = true

exclude_patterns = [
  "tests/**",
]

test_patterns = [
  "tests/**"
]

[[transformers]]
name = "clang-format"
