name: Code style check

on:
  workflow_call:

permissions: {}

jobs:
  style:
    name: Code style check
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    defaults:
      run:
        shell: bash
    steps:
      - uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 50
          submodules: recursive

      - name: Setup clang-format
        run: |
          wget https://apt.llvm.org/llvm.sh
          chmod +x llvm.sh
          sudo ./llvm.sh 21
          sudo apt install -y clang-format-21
          sudo update-alternatives --install /usr/bin/clang-format clang-format /usr/bin/clang-format-21 210

      - name: Check code format
        run: |
          bash tools/builder/check_code_format.sh

      - name: Check format of markdown files
        uses: DavidAnson/markdownlint-cli2-action@v22
        with:
          globs: "**/*.md"
